### ISSUE TITLE
UIkit Version 2.17.0

### ISSUE THREAD

**Issue by ponciusz** [marsec/uikit-sass-rails#6]
It is possible to update to new UIkit??

**Comment by cworreschk** [comment]
I'm currently working to release a new version with UIkit 2.18.0 . I think it will be ready in a couple of days.

**Comment by mayatskiy** [comment]
Any updates?

**Comment by arnoldandpearn** [comment]
I've updated the gem with the (current latest) UIKit 2.20.0 and have submitted a pull request but not seen any more movement. This is my first contribution and I barely understand the Git processes so any guidance on something I may have done wrong or missed out would be gratefully received.

**Comment by cworreschk** [comment]
@arnoldandpearn I'll check your pull request. Thank you very much for this.

**Comment by arnoldandpearn** [comment]
Thanks @cworreschk – let me know if I need to do anything else.

**Comment by cworreschk** [comment]
With help from @arnoldandpearn I published a new version. It includes UIkit 2.20.3. Have fun :sunglasses: 
https://github.com/marsec/uikit-sass-rails/releases/tag/1.4.0
